spring:
  application:
    name: mobile-sales
  datasource:
    username: root
    password: 514415
    url: jdbc:mysql://localhost:3306/mobile_sales?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Australia/Sydney&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: tut02group03
  #token lifecycle
  expire-hours: 24
server:
  port: 8080
